// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pb/simulation.proto

package simulation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent by the World to tell actors to update their state
type Tick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaTime     int64                  `protobuf:"varint,1,opt,name=delta_time,json=deltaTime,proto3" json:"delta_time,omitempty"` // Time elapsed since last frame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_pb_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_pb_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *Tick) GetDeltaTime() int64 {
	if x != nil {
		return x.DeltaTime
	}
	return 0
}

// Sent by the World to ask for current status
type GetState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetState) Reset() {
	*x = GetState{}
	mi := &file_pb_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetState) ProtoMessage() {}

func (x *GetState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetState.ProtoReflect.Descriptor instead.
func (*GetState) Descriptor() ([]byte, []int) {
	return file_pb_simulation_proto_rawDescGZIP(), []int{1}
}

// The response containing the actor's data
type ActorState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"` // "RED" or "BLUE"
	PositionX     float64                `protobuf:"fixed64,3,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY     float64                `protobuf:"fixed64,4,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	VelocityX     float64                `protobuf:"fixed64,5,opt,name=velocity_x,json=velocityX,proto3" json:"velocity_x,omitempty"`
	VelocityY     float64                `protobuf:"fixed64,6,opt,name=velocity_y,json=velocityY,proto3" json:"velocity_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorState) Reset() {
	*x = ActorState{}
	mi := &file_pb_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorState) ProtoMessage() {}

func (x *ActorState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorState.ProtoReflect.Descriptor instead.
func (*ActorState) Descriptor() ([]byte, []int) {
	return file_pb_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *ActorState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActorState) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ActorState) GetPositionX() float64 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *ActorState) GetPositionY() float64 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *ActorState) GetVelocityX() float64 {
	if x != nil {
		return x.VelocityX
	}
	return 0
}

func (x *ActorState) GetVelocityY() float64 {
	if x != nil {
		return x.VelocityY
	}
	return 0
}

// Perception is sent by the world to tell an actor what neighbors are visible
type Perception struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*ActorState          `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Friends       []*ActorState          `protobuf:"bytes,2,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Perception) Reset() {
	*x = Perception{}
	mi := &file_pb_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Perception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Perception) ProtoMessage() {}

func (x *Perception) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Perception.ProtoReflect.Descriptor instead.
func (*Perception) Descriptor() ([]byte, []int) {
	return file_pb_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *Perception) GetTargets() []*ActorState {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Perception) GetFriends() []*ActorState {
	if x != nil {
		return x.Friends
	}
	return nil
}

// Convert message is the command to switch teams
type Convert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetColor   string                 `protobuf:"bytes,1,opt,name=target_color,json=targetColor,proto3" json:"target_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Convert) Reset() {
	*x = Convert{}
	mi := &file_pb_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Convert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Convert) ProtoMessage() {}

func (x *Convert) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Convert.ProtoReflect.Descriptor instead.
func (*Convert) Descriptor() ([]byte, []int) {
	return file_pb_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *Convert) GetTargetColor() string {
	if x != nil {
		return x.TargetColor
	}
	return ""
}

// Sent by Individual -> World
type ReportStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ActorState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatus) Reset() {
	*x = ReportStatus{}
	mi := &file_pb_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatus) ProtoMessage() {}

func (x *ReportStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatus.ProtoReflect.Descriptor instead.
func (*ReportStatus) Descriptor() ([]byte, []int) {
	return file_pb_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *ReportStatus) GetState() *ActorState {
	if x != nil {
		return x.State
	}
	return nil
}

// Sent by World -> UI (via channel, or actor if UI is an actor)
type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []*ActorState          `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	RedCount      int32                  `protobuf:"varint,2,opt,name=red_count,json=redCount,proto3" json:"red_count,omitempty"`
	BlueCount     int32                  `protobuf:"varint,3,opt,name=blue_count,json=blueCount,proto3" json:"blue_count,omitempty"`
	IsGameOver    bool                   `protobuf:"varint,4,opt,name=is_game_over,json=isGameOver,proto3" json:"is_game_over,omitempty"`
	Winner        string                 `protobuf:"bytes,5,opt,name=winner,proto3" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_pb_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_pb_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *WorldSnapshot) GetActors() []*ActorState {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *WorldSnapshot) GetRedCount() int32 {
	if x != nil {
		return x.RedCount
	}
	return 0
}

func (x *WorldSnapshot) GetBlueCount() int32 {
	if x != nil {
		return x.BlueCount
	}
	return 0
}

func (x *WorldSnapshot) GetIsGameOver() bool {
	if x != nil {
		return x.IsGameOver
	}
	return false
}

func (x *WorldSnapshot) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

// UpdateConfig Simple struct to update config (can be moved to proto)
type UpdateConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DetectionRadius float64                `protobuf:"fixed64,1,opt,name=DetectionRadius,proto3" json:"DetectionRadius,omitempty"`
	DefenseRadius   float64                `protobuf:"fixed64,2,opt,name=DefenseRadius,proto3" json:"DefenseRadius,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateConfig) Reset() {
	*x = UpdateConfig{}
	mi := &file_pb_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfig) ProtoMessage() {}

func (x *UpdateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pb_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfig.ProtoReflect.Descriptor instead.
func (*UpdateConfig) Descriptor() ([]byte, []int) {
	return file_pb_simulation_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateConfig) GetDetectionRadius() float64 {
	if x != nil {
		return x.DetectionRadius
	}
	return 0
}

func (x *UpdateConfig) GetDefenseRadius() float64 {
	if x != nil {
		return x.DefenseRadius
	}
	return 0
}

var File_pb_simulation_proto protoreflect.FileDescriptor

const file_pb_simulation_proto_rawDesc = "" +
	"\n" +
	"\x13pb/simulation.proto\x12\x02pb\"%\n" +
	"\x04Tick\x12\x1d\n" +
	"\n" +
	"delta_time\x18\x01 \x01(\x03R\tdeltaTime\"\n" +
	"\n" +
	"\bGetState\"\xae\x01\n" +
	"\n" +
	"ActorState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"position_x\x18\x03 \x01(\x01R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\x04 \x01(\x01R\tpositionY\x12\x1d\n" +
	"\n" +
	"velocity_x\x18\x05 \x01(\x01R\tvelocityX\x12\x1d\n" +
	"\n" +
	"velocity_y\x18\x06 \x01(\x01R\tvelocityY\"`\n" +
	"\n" +
	"Perception\x12(\n" +
	"\atargets\x18\x01 \x03(\v2\x0e.pb.ActorStateR\atargets\x12(\n" +
	"\afriends\x18\x02 \x03(\v2\x0e.pb.ActorStateR\afriends\",\n" +
	"\aConvert\x12!\n" +
	"\ftarget_color\x18\x01 \x01(\tR\vtargetColor\"4\n" +
	"\fReportStatus\x12$\n" +
	"\x05state\x18\x01 \x01(\v2\x0e.pb.ActorStateR\x05state\"\xad\x01\n" +
	"\rWorldSnapshot\x12&\n" +
	"\x06actors\x18\x01 \x03(\v2\x0e.pb.ActorStateR\x06actors\x12\x1b\n" +
	"\tred_count\x18\x02 \x01(\x05R\bredCount\x12\x1d\n" +
	"\n" +
	"blue_count\x18\x03 \x01(\x05R\tblueCount\x12 \n" +
	"\fis_game_over\x18\x04 \x01(\bR\n" +
	"isGameOver\x12\x16\n" +
	"\x06winner\x18\x05 \x01(\tR\x06winner\"^\n" +
	"\fUpdateConfig\x12(\n" +
	"\x0fDetectionRadius\x18\x01 \x01(\x01R\x0fDetectionRadius\x12$\n" +
	"\rDefenseRadius\x18\x02 \x01(\x01R\rDefenseRadiusB5Z3github.com/lao-tseu-is-alive/go-swarm-simulation/pbb\x06proto3"

var (
	file_pb_simulation_proto_rawDescOnce sync.Once
	file_pb_simulation_proto_rawDescData []byte
)

func file_pb_simulation_proto_rawDescGZIP() []byte {
	file_pb_simulation_proto_rawDescOnce.Do(func() {
		file_pb_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_simulation_proto_rawDesc), len(file_pb_simulation_proto_rawDesc)))
	})
	return file_pb_simulation_proto_rawDescData
}

var file_pb_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_simulation_proto_goTypes = []any{
	(*Tick)(nil),          // 0: pb.Tick
	(*GetState)(nil),      // 1: pb.GetState
	(*ActorState)(nil),    // 2: pb.ActorState
	(*Perception)(nil),    // 3: pb.Perception
	(*Convert)(nil),       // 4: pb.Convert
	(*ReportStatus)(nil),  // 5: pb.ReportStatus
	(*WorldSnapshot)(nil), // 6: pb.WorldSnapshot
	(*UpdateConfig)(nil),  // 7: pb.UpdateConfig
}
var file_pb_simulation_proto_depIdxs = []int32{
	2, // 0: pb.Perception.targets:type_name -> pb.ActorState
	2, // 1: pb.Perception.friends:type_name -> pb.ActorState
	2, // 2: pb.ReportStatus.state:type_name -> pb.ActorState
	2, // 3: pb.WorldSnapshot.actors:type_name -> pb.ActorState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_simulation_proto_init() }
func file_pb_simulation_proto_init() {
	if File_pb_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_simulation_proto_rawDesc), len(file_pb_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_simulation_proto_goTypes,
		DependencyIndexes: file_pb_simulation_proto_depIdxs,
		MessageInfos:      file_pb_simulation_proto_msgTypes,
	}.Build()
	File_pb_simulation_proto = out.File
	file_pb_simulation_proto_goTypes = nil
	file_pb_simulation_proto_depIdxs = nil
}
